ALTER TYPE "RoleKey" ADD VALUE IF NOT EXISTS 'OWNER';
ALTER TYPE "RoleKey" ADD VALUE IF NOT EXISTS 'ADMIN';
ALTER TYPE "RoleKey" ADD VALUE IF NOT EXISTS 'MANAGER';
ALTER TYPE "RoleKey" ADD VALUE IF NOT EXISTS 'FINANCE';
ALTER TYPE "RoleKey" ADD VALUE IF NOT EXISTS 'OPERATIONS';
ALTER TYPE "RoleKey" ADD VALUE IF NOT EXISTS 'VIEWER';
